name: FrontEnd CI PipeLine

# Workflow를 실행시키기 위한 Event 목록
on:
  pull_request:
    branches:
      - main
    paths:
      - 'frontend/**'
  push:
    branches:
      - main
    paths:
      - 'frontend/**'

  # 해당 옵션을 통해 사용자가 직접 Actions 탭에서 Workflow를 실행시킬 수 있음
  workflow_dispatch:

defaults:
  run:
    working-directory: ./frontend

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          script: sudo sh projects/bookmore/deploy-fe.sh